CAMERA_SPECS = {
    "X-T5": [
        ("Image Sensor", "40.2MP X-Trans CMOS 5 HR BSI"),
        ("Image Processing Engine", "X-Processor 5"),
        ("EVF", "Yes - 3.69M-dot OLED, 0.8x"),
        ("LCD Monitor", "3.0-inch 3-way tilt touchscreen"),
        ("IBIS", "Yes - 5-axis, up to 7.0 stops"),
        ("Weather Sealed", "Yes - 56 points"),
    ],
    "X-H2": [
        ("Image Sensor", "40.2MP X-Trans CMOS 5 HR BSI"),
        ("Image Processing Engine", "X-Processor 5"),
        ("EVF", "Yes - 5.76M-dot OLED, 0.8x"),
        ("LCD Monitor", "3.0-inch vari-angle touchscreen"),
        ("IBIS", "Yes - 5-axis, up to 7.0 stops"),
        ("Weather Sealed", "Yes"),
    ],
    "X-E5": [
        ("Image Sensor", "40.2MP X-Trans CMOS 5 HR BSI"),
        ("Image Processing Engine", "X-Processor 5"),
        ("EVF", "Yes - 2.36M-dot OLED, 0.62x"),
        ("LCD Monitor", "3.0-inch tilt touchscreen"),
        ("IBIS", "Yes - 5-axis, up to 7.0 stops"),
        ("Weather Sealed", "No"),
    ],
    "X-S20": [
        ("Image Sensor", "26.1MP X-Trans CMOS 4 BSI"),
        ("Image Processing Engine", "X-Processor 5"),
        ("EVF", "Yes - 2.36M-dot OLED, 0.62x"),
        ("LCD Monitor", "3.0-inch vari-angle touchscreen"),
        ("IBIS", "Yes - 5-axis, up to 7.0 stops"),
        ("Weather Sealed", "Yes"),
    ],
    "X-T50": [
        ("Image Sensor", "40.2MP X-Trans CMOS 5 HR BSI"),
        ("Image Processing Engine", "X-Processor 5"),
        ("EVF", "Yes - 2.36M-dot OLED, 0.62x"),
        ("LCD Monitor", "3.0-inch vari-angle touchscreen"),
        ("IBIS", "Yes - 5-axis, up to 7.0 stops"),
        ("Weather Sealed", "No"),
    ],
    "X-T30 III": [
        ("Image Sensor", "26.1MP X-Trans CMOS 4 BSI"),
        ("Image Processing Engine", "X-Processor 5"),
        ("EVF", "Yes - 2.36M-dot OLED, 0.62x"),
        ("LCD Monitor", "3.0-inch tilt touchscreen"),
        ("IBIS", "No"),
        ("Weather Sealed", "No"),
    ],
    "X-M5": [
        ("Image Sensor", "26.1MP X-Trans CMOS 4 BSI"),
        ("Image Processing Engine", "X-Processor 5"),
        ("EVF", "No"),
        ("LCD Monitor", "3.0-inch vari-angle touchscreen"),
        ("IBIS", "No"),
        ("Weather Sealed", "No"),
    ],
    "X-M5 CN": [
        ("Image Sensor", "26.1MP X-Trans CMOS 4 BSI"),
        ("Image Processing Engine", "X-Processor 5"),
        ("EVF", "No"),
        ("LCD Monitor", "3.0-inch vari-angle touchscreen"),
        ("IBIS", "No"),
        ("Weather Sealed", "No"),
    ],
    "X-T200": [
        ("Image Sensor", "24.2MP APS-C Bayer CMOS BSI"),
        ("Image Processing Engine", "X-Processor 4"),
        ("EVF", "Yes - 2.36M-dot OLED, 0.62x"),
        ("LCD Monitor", "3.5-inch vari-angle touchscreen"),
        ("IBIS", "No"),
        ("Weather Sealed", "No"),
    ],
    "X half": [
        ("Image Sensor", "18MP 1-inch BSI CMOS (vertical mount)"),
        ("Image Processing Engine", "X-Processor 5"),
        ("EVF", "Optical only - 0.38x, no overlays"),
        ("LCD Monitor", "Rear LCD + sub front screen"),
        ("IBIS", "No"),
        ("Weather Sealed", "No"),
    ],
    "GFX-50R": [
        ("Image Sensor", "51.4MP Medium Format CMOS (43.8x32.9mm)"),
        ("Image Processing Engine", "X-Processor Pro"),
        ("EVF", "Yes - 3.69M-dot OLED, 0.77x"),
        ("LCD Monitor", "3.2-inch 2-way tilt touchscreen"),
        ("IBIS", "No"),
        ("Weather Sealed", "Yes - dust & moisture resistant"),
    ],
    "GFX100RF": [
        ("Image Sensor", "102MP Medium Format BSI CMOS II (43.8x32.9mm)"),
        ("Image Processing Engine", "X-Processor 5"),
        ("EVF", "Yes - 5.76M-dot OLED, 0.84x"),
        ("LCD Monitor", "3.2-inch 3-way tilt touchscreen"),
        ("IBIS", "No"),
        ("Weather Sealed", "Partial - adapter + filter required"),
    ],
}
